In [2]:
from sklearn import metrics

# Constants
C="Cat"
F="Fish"
H="Hen"

# True values
y_true = [C,C,C,C,C,C, F,F,F,F,F,F,F,F,F,F, H,H,H,H,H,H,H,H,H]
# Predicted values
y_pred = [C,C,C,C,H,F, C,C,C,C,C,C,H,H,F,F, C,C,C,H,H,H,H,H,H]

# Print the confusion matrix
print(metrics.confusion_matrix(y_true, y_pred))

# Print the precision and recall, among other metrics
print(metrics.classification_report(y_true, y_pred, digits=3))

[[4 1 1]
 [6 2 2]
 [3 0 6]]
              precision    recall  f1-score   support

         Cat      0.308     0.667     0.421         6
        Fish      0.667     0.200     0.308        10
         Hen      0.667     0.667     0.667         9

    accuracy                          0.480        25
   macro avg      0.547     0.511     0.465        25
weighted avg      0.581     0.480     0.464        25



In [5]:
#explanation of micro-F1 and macro-F1 calculation

#https://towardsdatascience.com/multi-class-metrics-made-simple-part-ii-the-f1-score-ebe8b2c2ca1

#micro-F-1= micro-precisioon = micro-recall = accuracy



import numpy as np

from sklearn.metrics import precision_recall_fscore_support

from sklearn.metrics import classification_report




y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig', 'pig'])

y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog', 'pig'])




#Calculate metrics globally by counting the total true positives, false negatives and false positives.

score1 = precision_recall_fscore_support(y_true, y_pred, labels=['dog','cat','pig'], average='micro')

# (0.33..., 0.33..., 0.33..., None)

In [6]:
score1

(0.42857142857142855, 0.42857142857142855, 0.42857142857142855, None)

In [10]:
# y_true = [2, 1, 4, 4, 0, 1, 1, 2, 3, 4, 1, 4, 1, 3, 0, 2, 4, 4, 2, 0, 1, 2, 1, 3, 4, 4, 2, 4, 3, 1, 4, 3, 0, 1, 3, 1, 3, 3, 0, 3, 3, 0, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 3, 2, 1, 4, 3, 1, 4, 1, 2, 1, 3, 0, 2, 4, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 0, 1, 3, 1, 3, 3, 2, 3, 2, 1, 1, 4, 1, 4, 1, 1, 4, 4, 1, 0, 1, 4, 0, 2, 3, 3, 2, 1, 1, 3, 1, 1, 1, 2, 1, 3, 1, 2, 4, 0, 1, 0, 1, 3, 1, 2, 3, 3, 0, 1, 1, 0, 1, 4, 4, 1, 4, 1, 3, 0, 1, 3, 3, 2, 3, 2, 1, 3, 1, 1, 1, 4, 3, 1, 0, 3, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 2, 1, 3, 0, 1, 2, 3, 3, 0, 2, 0, 4, 3, 0, 0, 1, 1, 0, 0, 1, 3, 1, 1, 1, 3, 2, 4, 4, 1, 4, 4, 3, 2, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 4, 1, 2, 4, 0, 1, 4, 3, 4, 3, 0, 1, 1, 4, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 3, 3, 2, 3, 2, 3, 0, 1, 4, 3, 2, 1, 2, 3, 1, 2, 2, 3, 2, 1, 1, 2, 0, 2, 2, 1, 1, 2, 2, 4, 3, 3, 2, 2, 3, 1, 2, 2, 1, 2, 1, 1, 1, 2, 3, 3, 4, 4, 0, 3, 3, 0, 3, 0, 0, 1, 2, 1, 3, 2, 4, 1, 3, 0, 3, 4, 2, 1, 1, 3, 1, 2, 1, 1, 4, 1, 2, 3, 1, 1, 3, 1, 1, 1, 4, 0, 4, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 1, 4, 4, 3, 2, 1, 1, 2, 1, 3, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 0, 3, 1, 1, 1, 4, 1, 1, 0, 1, 3, 0, 1, 2, 1, 3, 3, 2, 2, 3, 2, 2, 3, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 0, 1, 1, 1, 3, 2, 0, 1, 1, 1, 3, 0, 3, 3, 1, 3, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 3, 0, 2, 1, 4, 4, 3, 3, 2, 1, 0, 1, 0, 1, 0, 1, 2, 1, 2, 3, 3, 2, 3, 2, 1, 2, 1, 2, 3, 2, 1, 3, 4, 0, 1, 3, 3, 1, 1, 1, 2, 3, 1, 1, 4, 0, 4, 0, 1, 1, 2, 3, 0, 0, 2, 3, 1, 3, 3, 1, 1, 2, 1, 3, 3, 1, 3, 1, 1, 1, 3, 1, 3, 1, 2, 4, 1, 4, 1, 3, 2, 3, 1, 1, 1, 0, 1, 1, 1, 1, 3, 0, 3, 1, 2, 1, 1, 3, 2, 1, 3, 1, 2, 3, 2, 3, 3, 1, 1, 1, 1, 2, 4, 1, 2, 1, 3, 0, 1, 2, 3, 1, 2, 3, 2, 1, 4, 1, 4, 4, 1, 2, 2, 1, 1, 1, 1, 0, 4, 1, 3, 2, 2, 2, 2, 1, 1, 0, 1, 2, 4, 1, 2, 2, 3, 3, 3, 2, 0, 3, 0, 1, 4, 1, 4, 1, 0, 2, 1, 2, 1, 4, 2, 4, 1, 1, 2, 4, 4, 4, 1, 2, 2, 1, 4, 1, 2, 4, 1, 2, 2, 3, 2, 3, 1, 2, 3, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 1, 3, 1, 3, 3, 1, 2, 2, 4, 3, 2, 0, 1, 4, 2, 3, 2, 1, 2, 1, 1, 4, 4, 4, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 4, 2, 2, 1, 2, 1, 1, 3, 0, 0, 2, 0, 0, 1, 0, 1, 3, 0, 0, 3, 1, 1, 2, 4, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 4, 3, 2, 1, 2, 1, 2, 1, 3, 2, 2, 4, 2, 1, 3, 1, 1, 2, 2, 1, 3, 3, 3, 1, 3, 2, 1, 2, 1, 2, 3, 4, 1, 2, 4, 1, 4, 2, 1, 4, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 4, 2, 4, 4, 3, 1, 2, 4, 4, 3, 3, 2, 1, 3, 2, 3, 2, 2, 1, 1, 4, 1, 1, 1, 2, 1, 2, 2, 1, 0, 4, 0, 1, 2, 2, 3, 1, 3, 2, 3, 3, 4, 3, 1, 2, 3, 1, 3, 2, 4, 2, 4, 2, 1, 2, 3, 0, 0, 1, 2, 4, 4, 2, 1, 2, 3, 2, 0, 4, 0, 0, 3, 2, 1, 1, 4, 1, 1, 2, 1, 4, 2, 2, 1, 1, 1, 3, 3, 2, 4, 4, 3, 3, 3, 2, 4, 0, 1, 2, 0, 4, 2, 3, 3, 3, 1, 3, 4, 2, 3, 3, 3, 2, 3, 4, 1, 2, 3, 3, 2, 0, 3, 1, 1, 2, 3, 3, 3, 3, 3, 3, 4, 3, 1, 1, 3, 3, 0, 3, 4, 3, 3, 4, 3, 2, 4, 3, 3, 3, 1, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 4, 2, 3, 3, 3, 4, 0, 3, 1, 4, 1, 3, 0, 4, 4, 1, 3, 2, 3, 3, 3, 3, 0, 0, 1, 3, 1, 3, 3, 4, 3, 3, 3, 3, 3, 1, 3, 3, 3, 4, 1, 3, 2, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 1, 4, 1, 3, 3, 3, 3, 2, 1, 3, 3, 3, 1, 3, 3, 0, 0, 3, 4, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 4, 4, 0, 3, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 3, 0, 1, 0, 4, 1, 0, 3, 4, 1, 3, 1, 0, 1, 3, 2, 0, 1, 3, 1, 3, 4, 3, 2, 1, 3, 0, 1, 1, 3, 1, 2, 1, 1, 3, 3, 3, 0, 3, 1, 3, 0, 1, 4, 3, 4, 1, 1, 3, 3, 1, 3, 0, 0, 3, 1, 4, 1, 3, 3, 1, 3, 3, 2, 1, 1, 3, 4, 1, 3, 1, 3, 1, 1, 1, 3, 3, 1, 3, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 4, 1, 3, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 0, 3, 4, 4, 4, 4, 1, 3, 3, 1, 4, 3, 3, 4, 1, 2, 1, 0, 1]
# y_pred = [0, 1, 0, 4, 1, 1, 1, 2, 3, 0, 1, 0, 1, 3, 4, 2, 4, 4, 2, 1, 1, 0, 1, 3, 4, 0, 2, 0, 3, 1, 0, 0, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 0, 3, 1, 0, 1, 2, 0, 3, 4, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 3, 1, 3, 1, 3, 3, 2, 3, 2, 1, 1, 4, 1, 4, 1, 1, 0, 0, 1, 4, 1, 0, 2, 0, 3, 3, 2, 1, 1, 3, 1, 1, 1, 2, 1, 3, 1, 2, 0, 1, 0, 1, 0, 3, 1, 2, 3, 3, 2, 1, 1, 2, 1, 4, 4, 1, 4, 1, 3, 3, 1, 3, 3, 2, 3, 2, 1, 3, 1, 1, 1, 0, 3, 0, 2, 3, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 2, 1, 3, 3, 1, 2, 3, 3, 1, 0, 4, 0, 3, 4, 4, 1, 1, 4, 1, 1, 3, 1, 1, 1, 3, 2, 4, 4, 1, 4, 4, 3, 2, 1, 2, 1, 0, 1, 1, 2, 1, 4, 1, 4, 0, 2, 4, 4, 1, 4, 3, 4, 3, 1, 1, 1, 4, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 3, 3, 2, 3, 2, 3, 3, 1, 4, 3, 2, 1, 2, 3, 1, 2, 2, 3, 2, 1, 1, 2, 2, 0, 2, 1, 1, 2, 2, 4, 3, 3, 2, 2, 3, 1, 2, 2, 1, 2, 1, 1, 1, 0, 3, 3, 4, 4, 4, 3, 3, 1, 3, 1, 4, 1, 2, 0, 3, 2, 0, 1, 3, 2, 3, 4, 0, 1, 1, 3, 1, 2, 1, 1, 4, 1, 2, 3, 0, 1, 3, 1, 1, 1, 4, 4, 4, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 1, 4, 4, 3, 2, 1, 1, 2, 1, 3, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 2, 1, 0, 4, 1, 4, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0, 2, 3, 1, 1, 1, 4, 1, 1, 1, 1, 0, 1, 1, 2, 1, 3, 3, 2, 2, 3, 2, 2, 3, 1, 1, 0, 1, 1, 1, 3, 3, 1, 1, 2, 1, 1, 0, 3, 2, 4, 1, 1, 1, 3, 4, 3, 3, 1, 3, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 0, 2, 2, 0, 4, 4, 3, 3, 2, 1, 2, 1, 1, 1, 4, 0, 0, 1, 2, 3, 3, 2, 3, 2, 1, 0, 1, 2, 3, 0, 1, 3, 0, 2, 1, 3, 3, 1, 1, 0, 2, 3, 0, 1, 0, 4, 4, 4, 1, 1, 2, 3, 1, 2, 2, 3, 0, 3, 3, 1, 1, 2, 1, 3, 3, 1, 3, 0, 0, 1, 3, 1, 3, 1, 2, 4, 1, 4, 1, 3, 2, 3, 1, 0, 1, 2, 0, 1, 1, 1, 3, 2, 3, 1, 2, 1, 1, 3, 2, 1, 3, 1, 2, 3, 2, 3, 0, 1, 1, 1, 1, 2, 4, 1, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 2, 1, 0, 1, 4, 4, 1, 2, 2, 1, 1, 1, 0, 4, 4, 1, 3, 2, 2, 2, 2, 1, 0, 2, 1, 2, 4, 1, 0, 2, 0, 3, 3, 2, 2, 3, 2, 1, 4, 1, 4, 1, 2, 2, 1, 2, 1, 4, 2, 4, 0, 1, 2, 4, 4, 4, 1, 2, 0, 1, 4, 1, 2, 4, 1, 2, 2, 3, 2, 3, 1, 2, 3, 1, 2, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 3, 1, 3, 3, 1, 2, 2, 4, 3, 0, 1, 0, 4, 0, 3, 2, 1, 2, 0, 1, 4, 4, 4, 2, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 0, 3, 2, 0, 0, 0, 1, 2, 1, 1, 3, 4, 2, 0, 3, 3, 1, 2, 1, 3, 2, 2, 3, 1, 1, 2, 4, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 3, 0, 1, 2, 1, 2, 1, 3, 2, 0, 4, 2, 1, 3, 1, 1, 2, 2, 1, 3, 3, 3, 1, 3, 2, 1, 2, 1, 2, 3, 4, 1, 2, 4, 1, 4, 2, 1, 4, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 4, 0, 4, 4, 3, 1, 2, 4, 4, 3, 3, 2, 1, 3, 2, 3, 2, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 4, 2, 1, 2, 2, 3, 1, 3, 2, 3, 0, 4, 3, 1, 2, 3, 1, 3, 2, 4, 2, 4, 2, 1, 0, 3, 1, 2, 1, 0, 4, 4, 0, 0, 2, 3, 2, 3, 4, 2, 2, 0, 2, 1, 1, 4, 1, 1, 2, 1, 4, 2, 2, 1, 1, 1, 3, 3, 2, 4, 4, 3, 3, 3, 2, 4, 1, 1, 2, 4, 4, 0, 3, 3, 3, 1, 3, 4, 2, 3, 3, 3, 2, 3, 4, 1, 2, 3, 3, 2, 4, 3, 1, 0, 2, 3, 3, 3, 3, 3, 3, 4, 3, 1, 1, 3, 3, 1, 3, 0, 3, 3, 0, 3, 2, 4, 3, 3, 3, 1, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 3, 4, 2, 3, 3, 3, 4, 1, 3, 0, 4, 1, 3, 4, 4, 0, 1, 3, 0, 3, 3, 0, 3, 1, 1, 1, 3, 1, 3, 3, 0, 3, 3, 3, 3, 3, 1, 3, 3, 3, 4, 1, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 4, 1, 3, 3, 3, 3, 0, 0, 0, 3, 3, 1, 3, 3, 2, 1, 3, 0, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 4, 4, 1, 3, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 3, 4, 1, 1, 4, 0, 1, 3, 0, 1, 3, 1, 1, 1, 3, 0, 2, 1, 3, 1, 3, 0, 3, 2, 1, 3, 2, 1, 1, 3, 1, 2, 0, 1, 3, 3, 3, 4, 3, 1, 3, 2, 1, 0, 3, 0, 1, 1, 3, 0, 1, 0, 3, 3, 3, 1, 0, 1, 3, 3, 1, 3, 3, 2, 1, 1, 3, 4, 1, 3, 1, 3, 1, 1, 1, 3, 3, 1, 3, 2, 1, 1, 3, 1, 1, 1, 3, 3, 1, 4, 1, 3, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 3, 3, 0, 4, 4, 4, 1, 3, 3, 1, 4, 3, 3, 0, 1, 2, 1, 1, 1]

In [13]:
y_true = [0, 3, 5, 3, 3, 4, 3, 3, 1, 4, 4, 4, 4, 4, 4, 5, 3, 3, 5, 5, 0, 5, 5, 5, 0, 5, 0, 5, 4, 4, 0, 3, 0, 3, 3, 1, 5, 5, 0, 5, 5, 5, 0, 4, 4, 1, 1, 5, 5, 5, 5, 0, 1, 1, 5, 5, 5, 5, 5, 5, 3, 3, 5, 0, 1, 4, 0, 0, 0, 5, 0, 0, 4, 0, 3, 3, 1, 1, 5, 4, 0, 5, 5, 5, 0, 0, 3, 3, 0, 0, 0, 0, 1, 1, 5, 0, 4, 0, 4, 4, 3, 1, 5, 3, 3, 0, 0, 0, 0, 3, 0, 4, 5, 5, 5, 1, 5, 5, 5, 4, 1, 1, 0, 4, 1, 4, 3, 1, 3, 3, 5, 0, 3, 3, 1, 1, 1, 3, 3, 5, 3, 4, 4, 4, 4, 3, 1, 1, 0, 1, 5, 4, 0, 3, 3, 5, 5, 5, 4, 4, 4, 3, 4, 0, 5, 0, 1, 0, 0, 5, 3, 5, 5, 5, 5, 5, 5, 4, 0, 5, 0, 5, 1, 4, 1, 1, 5, 4, 0, 4, 4, 5, 4, 5, 5, 5, 1, 5, 4, 4, 1, 1, 4, 4, 1, 4, 4, 1, 1, 1, 0, 5, 5, 1, 1, 3, 3, 1, 3, 0, 4, 4, 1, 5, 5, 5, 1, 0, 1, 4, 4, 4, 5, 3, 3, 1, 4, 4, 4, 4, 4, 1, 5, 5, 1, 5, 5, 5, 5, 4, 0, 0, 1, 5, 1, 3, 1, 4, 1, 5, 5, 5, 3, 1, 0, 4, 4, 5, 1, 5, 3, 3, 3, 3, 5, 5, 1, 3, 5, 3, 3, 3, 3, 0, 3, 3, 3, 5, 3, 3, 0, 1, 1, 1, 1, 4, 0, 1, 0, 1, 3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 0, 1, 1, 5, 5, 3, 0, 5, 5, 4, 1, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 1, 0, 0, 0, 0, 3, 3, 0, 5, 5, 5, 0, 5, 5, 3, 1, 3, 0, 0, 3, 4, 0, 3, 1, 0, 3, 4, 3, 3, 1, 4, 4, 3, 3, 1, 0, 3, 3, 3, 3, 3, 3, 4, 3, 1, 3, 4, 3, 4, 1, 1, 5, 0, 0, 0, 3, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 3, 1, 0, 3, 3, 3, 3, 3, 5, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 4, 4, 0, 0, 4, 4, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 4, 4, 0, 0, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 5]
y_pred = [5, 0, 5, 3, 3, 0, 0, 0, 1, 4, 0, 4, 0, 0, 4, 5, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 4, 3, 3, 3, 3, 3, 1, 5, 5, 5, 5, 5, 5, 4, 4, 4, 1, 1, 5, 5, 5, 5, 1, 0, 1, 5, 0, 5, 5, 5, 5, 0, 3, 0, 5, 1, 4, 1, 1, 1, 5, 5, 3, 4, 4, 3, 3, 1, 1, 5, 0, 1, 5, 5, 5, 3, 3, 3, 3, 3, 1, 4, 4, 1, 0, 5, 5, 4, 4, 4, 4, 3, 1, 5, 3, 3, 3, 5, 3, 3, 0, 4, 4, 0, 5, 5, 1, 0, 0, 0, 4, 1, 1, 4, 4, 1, 4, 3, 1, 3, 3, 5, 3, 3, 0, 1, 1, 1, 3, 3, 5, 3, 0, 0, 0, 0, 0, 1, 1, 1, 0, 5, 4, 4, 3, 3, 0, 0, 0, 4, 4, 4, 0, 4, 3, 0, 4, 1, 5, 3, 0, 3, 5, 0, 5, 5, 5, 5, 0, 5, 0, 1, 5, 0, 4, 0, 1, 5, 0, 5, 4, 0, 5, 0, 0, 0, 0, 1, 5, 4, 4, 0, 0, 4, 4, 1, 0, 4, 0, 1, 1, 3, 0, 5, 1, 1, 3, 0, 0, 0, 1, 0, 4, 1, 0, 0, 0, 1, 3, 0, 0, 4, 4, 0, 0, 0, 1, 4, 4, 0, 0, 4, 1, 5, 5, 1, 0, 0, 0, 0, 4, 3, 1, 1, 5, 1, 3, 1, 0, 1, 5, 5, 0, 3, 1, 1, 4, 4, 5, 1, 0, 3, 3, 3, 3, 0, 5, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 4, 1, 0, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 4, 3, 1, 1, 0, 0, 3, 3, 0, 0, 4, 1, 0, 0, 1, 3, 3, 3, 0, 0, 0, 0, 3, 0, 0, 3, 3, 0, 0, 3, 1, 1, 1, 0, 1, 1, 1, 1, 3, 3, 5, 0, 0, 5, 5, 5, 5, 3, 0, 3, 3, 4, 3, 4, 3, 3, 1, 3, 3, 4, 3, 3, 1, 4, 0, 3, 3, 1, 4, 3, 3, 3, 3, 3, 3, 4, 3, 0, 0, 0, 0, 0, 0, 1, 0, 3, 1, 4, 3, 4, 1, 1, 4, 3, 3, 1, 0, 3, 0, 1, 0, 0, 1, 3, 3, 3, 3, 3, 5, 2, 2, 2, 5, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 5, 5, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 5, 4, 4, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5]

In [15]:
score1 = precision_recall_fscore_support(y_true, y_pred, labels=[3, 1, 5, 4, 2],
                                         average='micro', zero_division=0)
score1[:-1]

(0.746268656716418, 0.7109004739336493, 0.7281553398058254)

In [17]:
score1 = precision_recall_fscore_support(y_true, y_pred, labels=[3, 1, 5, 4, 2],
                                         average='micro', zero_division=0)
score1[:-1]

(0.5725190839694656, 0.5725190839694656, 0.5725190839694656)

In [18]:
y_true_arr = np.asanyarray(y_true)
y_pred_arr = np.asanyarray(y_pred)

In [21]:
TP2 = np.sum((y_true_arr==y_pred_arr)&(y_true_arr!=0))
FP2 = np.sum((y_true_arr!=y_pred_arr)&(y_pred_arr!=0))
FN2 = np.sum((y_true_arr!=y_pred_arr)&(y_true_arr!=0))

In [22]:
TP2

300

In [23]:
FP2

102

In [24]:
FN2

122

In [25]:
TP2/(TP2+FP2)

0.746268656716418

In [26]:
TP2/(TP2+FN2)

0.7109004739336493